# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(936, 668)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.save.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon)
        self.save.setIconSize(QtCore.QSize(40, 35))
        self.save.setObjectName("save")
        self.gridLayout_8.addWidget(self.save, 3, 13, 1, 6)
        self.gain4 = QtWidgets.QLabel(self.centralwidget)
        self.gain4.setObjectName("gain4")
        self.gridLayout_8.addWidget(self.gain4, 8, 14, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setMinimum(-20)
        self.verticalSlider.setMaximum(20)
        self.verticalSlider.setProperty("value", 1)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.gridLayout_6.addWidget(self.verticalSlider, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 9, 3, 1, 2)
        self.play2 = QtWidgets.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/play-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play2.setIcon(icon1)
        self.play2.setIconSize(QtCore.QSize(30, 20))
        self.play2.setObjectName("play2")
        self.gridLayout_8.addWidget(self.play2, 16, 10, 1, 5)
        self.gain2 = QtWidgets.QLabel(self.centralwidget)
        self.gain2.setObjectName("gain2")
        self.gridLayout_8.addWidget(self.gain2, 8, 6, 1, 1)
        self.gain8 = QtWidgets.QLabel(self.centralwidget)
        self.gain8.setObjectName("gain8")
        self.gridLayout_8.addWidget(self.gain8, 8, 29, 1, 3)
        self.gain5 = QtWidgets.QLabel(self.centralwidget)
        self.gain5.setObjectName("gain5")
        self.gridLayout_8.addWidget(self.gain5, 8, 18, 1, 3)
        self.gain3 = QtWidgets.QLabel(self.centralwidget)
        self.gain3.setObjectName("gain3")
        self.gridLayout_8.addWidget(self.gain3, 8, 8, 1, 4)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_5, 16, 0, 1, 10)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_8.addLayout(self.gridLayout_2, 10, 0, 1, 1)
        self.gain9 = QtWidgets.QLabel(self.centralwidget)
        self.gain9.setObjectName("gain9")
        self.gridLayout_8.addWidget(self.gain9, 8, 32, 1, 3)
        self.gain10 = QtWidgets.QLabel(self.centralwidget)
        self.gain10.setObjectName("gain10")
        self.gridLayout_8.addWidget(self.gain10, 8, 35, 1, 3)
        self.gain7 = QtWidgets.QLabel(self.centralwidget)
        self.gain7.setObjectName("gain7")
        self.gridLayout_8.addWidget(self.gain7, 8, 26, 1, 3)
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_8.addWidget(self.graphicsView, 13, 1, 1, 37)
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.reset.setFont(font)
        self.reset.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset.setIcon(icon2)
        self.reset.setIconSize(QtCore.QSize(40, 35))
        self.reset.setObjectName("reset")
        self.gridLayout_8.addWidget(self.reset, 3, 5, 1, 3)
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.clear.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/eraser-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear.setIcon(icon3)
        self.clear.setIconSize(QtCore.QSize(40, 35))
        self.clear.setObjectName("clear")
        self.gridLayout_8.addWidget(self.clear, 2, 23, 2, 5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_8.addLayout(self.gridLayout, 1, 4, 3, 25)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_8.addLayout(self.gridLayout_4, 17, 0, 2, 38)
        self.verticalSlider_5 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_5.setMinimum(-20)
        self.verticalSlider_5.setMaximum(20)
        self.verticalSlider_5.setProperty("value", 1)
        self.verticalSlider_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_5.setObjectName("verticalSlider_5")
        self.gridLayout_8.addWidget(self.verticalSlider_5, 9, 19, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_8.addWidget(self.radioButton_2, 16, 24, 1, 3)
        self.gain1 = QtWidgets.QLabel(self.centralwidget)
        self.gain1.setObjectName("gain1")
        self.gridLayout_8.addWidget(self.gain1, 8, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 11, 3, 1, 3)
        self.verticalSlider_9 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_9.setMinimum(-20)
        self.verticalSlider_9.setMaximum(20)
        self.verticalSlider_9.setProperty("value", 1)
        self.verticalSlider_9.setTracking(False)
        self.verticalSlider_9.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_9.setObjectName("verticalSlider_9")
        self.gridLayout_8.addWidget(self.verticalSlider_9, 9, 33, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_8.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalSlider_7 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_7.setMinimum(-20)
        self.verticalSlider_7.setMaximum(20)
        self.verticalSlider_7.setProperty("value", 1)
        self.verticalSlider_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_7.setObjectName("verticalSlider_7")
        self.gridLayout_8.addWidget(self.verticalSlider_7, 9, 26, 1, 1)
        self.verticalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_3.setMinimum(-20)
        self.verticalSlider_3.setMaximum(20)
        self.verticalSlider_3.setProperty("value", 1)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.gridLayout_8.addWidget(self.verticalSlider_3, 9, 8, 1, 1)
        self.difference = QtWidgets.QPushButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.difference.setIcon(icon4)
        self.difference.setIconSize(QtCore.QSize(30, 20))
        self.difference.setObjectName("difference")
        self.gridLayout_8.addWidget(self.difference, 10, 18, 2, 5)
        self.verticalSlider_8 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_8.setMinimum(-20)
        self.verticalSlider_8.setMaximum(20)
        self.verticalSlider_8.setProperty("value", 1)
        self.verticalSlider_8.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_8.setObjectName("verticalSlider_8")
        self.gridLayout_8.addWidget(self.verticalSlider_8, 9, 29, 1, 1)
        self.verticalSlider_10 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_10.setMinimum(-20)
        self.verticalSlider_10.setMaximum(20)
        self.verticalSlider_10.setProperty("value", 1)
        self.verticalSlider_10.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_10.setObjectName("verticalSlider_10")
        self.gridLayout_8.addWidget(self.verticalSlider_10, 9, 36, 1, 1)
        self.graphicsView_2 = PlotWidget(self.centralwidget)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_8.addWidget(self.graphicsView_2, 18, 1, 1, 37)
        self.gain6 = QtWidgets.QLabel(self.centralwidget)
        self.gain6.setObjectName("gain6")
        self.gridLayout_8.addWidget(self.gain6, 8, 21, 1, 5)
        self.verticalSlider_4 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_4.setMinimum(-20)
        self.verticalSlider_4.setMaximum(20)
        self.verticalSlider_4.setProperty("value", 1)
        self.verticalSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_4.setProperty("eslam", "")
        self.verticalSlider_4.setObjectName("verticalSlider_4")
        self.gridLayout_8.addWidget(self.verticalSlider_4, 9, 14, 1, 1)
        self.verticalSlider_6 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_6.setMinimum(-20)
        self.verticalSlider_6.setMaximum(20)
        self.verticalSlider_6.setProperty("value", 1)
        self.verticalSlider_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_6.setObjectName("verticalSlider_6")
        self.gridLayout_8.addWidget(self.verticalSlider_6, 9, 23, 1, 1)
        self.verticalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_2.setMinimum(-20)
        self.verticalSlider_2.setMaximum(20)
        self.verticalSlider_2.setProperty("value", 1)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.gridLayout_8.addWidget(self.verticalSlider_2, 9, 6, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_8.addWidget(self.radioButton_3, 16, 29, 1, 5)
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_8.addWidget(self.radioButton, 16, 17, 1, 5)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_8.addLayout(self.gridLayout_7, 12, 0, 4, 38)
        self.play1 = QtWidgets.QPushButton(self.centralwidget)
        self.play1.setIcon(icon1)
        self.play1.setIconSize(QtCore.QSize(30, 20))
        self.play1.setObjectName("play1")
        self.gridLayout_8.addWidget(self.play1, 11, 9, 1, 6)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 9, 1, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 936, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionPlay1 = QtWidgets.QAction(MainWindow)
        self.actionPlay1.setObjectName("actionPlay1")
        self.actionplay_new = QtWidgets.QAction(MainWindow)
        self.actionplay_new.setObjectName("actionplay_new")
        self.menuFile.addAction(self.actionopen)
        self.menuEdit.addAction(self.actionReset)
        self.menuEdit.addAction(self.actionClear)
        self.menuEdit.addAction(self.actionSave)
        self.menuEdit.addAction(self.actionPlay1)
        self.menuEdit.addAction(self.actionplay_new)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RRE Sound Equalizer"))
        MainWindow.setWindowIcon(QtGui.QIcon('icons/icon2.png'))       
        self.save.setText(_translate("MainWindow", "Save"))
        self.gain4.setText(_translate("MainWindow", "TextLabel"))
        self.play2.setText(_translate("MainWindow", "Play Modified"))
        self.gain2.setText(_translate("MainWindow", "TextLabel"))
        self.gain8.setText(_translate("MainWindow", "TextLabel"))
        self.gain5.setText(_translate("MainWindow", "TextLabel"))
        self.gain3.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "       Frequency domain graph"))
        self.gain9.setText(_translate("MainWindow", "TextLabel"))
        self.gain10.setText(_translate("MainWindow", "TextLabel"))
        self.gain7.setText(_translate("MainWindow", "TextLabel"))
        self.reset.setText(_translate("MainWindow", "Reset"))
        self.clear.setText(_translate("MainWindow", "Clear"))
        self.radioButton_2.setText(_translate("MainWindow", "Hanning"))
        self.gain1.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "Time domain graph"))
        self.difference.setText(_translate("MainWindow", "Difference"))
        self.gain6.setText(_translate("MainWindow", "TextLabel"))
        self.radioButton_3.setText(_translate("MainWindow", "Hamming"))
        self.radioButton.setText(_translate("MainWindow", "Rectangular"))
        self.play1.setText(_translate("MainWindow", "Play Original"))
        self.label_11.setText(_translate("MainWindow", "  Gain (db)"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionopen.setStatusTip(_translate("MainWindow", "open a file"))
        self.actionopen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionReset.setStatusTip(_translate("MainWindow", "reset gains"))
        self.actionReset.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionClear.setStatusTip(_translate("MainWindow", "clear plots"))
        self.actionClear.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "save the file"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionPlay1.setText(_translate("MainWindow", "Play1"))
        self.actionPlay1.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.actionplay_new.setText(_translate("MainWindow", "play new"))
        self.actionplay_new.setStatusTip(_translate("MainWindow", "play after manipulations"))
        self.actionplay_new.setShortcut(_translate("MainWindow", "Ctrl+2"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
